//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Digita.Tustena {
    
    public partial class login {
        protected System.Web.UI.WebControls.DomValidators.RegexDomValidator LoginValidator;
        protected System.Web.UI.WebControls.TextBox TxtUsr;
        protected System.Web.UI.WebControls.TextBox TxtPwd;
        protected System.Web.UI.WebControls.Button Submit;
        protected System.Web.UI.WebControls.Label TxtMessage;
        protected System.Web.UI.WebControls.DomValidators.RegexDomValidator Validator1;
        protected System.Web.UI.WebControls.DomValidators.RequiredDomValidator Validator2;
        protected System.Web.UI.WebControls.DomValidators.RequiredDomValidator Validator3;
        protected System.Web.UI.WebControls.CheckBox CkbPL;
    }
}
