//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Digita.Tustena.MailingList {
    
    public partial class sendsms {
        protected System.Web.UI.HtmlControls.HtmlForm Form1;
        protected System.Web.UI.WebControls.TextBox TxtNumber;
        protected System.Web.UI.WebControls.TextBox TxtMessage;
        protected System.Web.UI.WebControls.LinkButton BtnSend;
        protected System.Web.UI.WebControls.Label MsgLabel;
    }
}
