//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Digita.Tustena {
    
    public partial class SearchDataStorage {
        protected System.Web.UI.HtmlControls.HtmlForm Default;
        protected System.Web.UI.WebControls.Label LblQuery;
        protected System.Web.UI.WebControls.TextBox txtQuery;
        protected System.Web.UI.WebControls.DomValidators.RequiredDomValidator reqValQuery;
        protected System.Web.UI.WebControls.Label LblQueryType;
        protected System.Web.UI.WebControls.DropDownList cboQueryType;
        protected System.Web.UI.WebControls.Label LblDirectory;
        protected System.Web.UI.WebControls.DropDownList cboDirectory;
        protected System.Web.UI.WebControls.Label LblSortOrder;
        protected System.Web.UI.WebControls.DropDownList cboSortBy;
        protected System.Web.UI.WebControls.DropDownList CboSortOrder;
        protected System.Web.UI.WebControls.Button BtnSearch;
        protected System.Web.UI.WebControls.Label LblResultCount;
        protected System.Web.UI.WebControls.DataGrid DgResultsGrid;
    }
}
