//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Digita.Tustena.Error {
    
    public partial class ErrorPage {
        protected System.Web.UI.HtmlControls.HtmlForm Form2;
        protected System.Web.UI.WebControls.Literal LtrError;
        protected System.Web.UI.HtmlControls.HtmlForm Form1;
    }
}
